modLoader = "javafml"
loaderVersion = "[40,)"
license = "GNU GPL 3.0"
issueTrackerURL="https://github.com/yzl210/TeamProjectE/issues"
[[mods]]
modId = "teamprojecte"
version = "${file.jarVersion}"
displayName = "Team ProjectE"
logoFile= "logo.png"
authors = "6LeoY"
description = '''
ProjectE knowledge and EMC syncing!
'''
[[dependencies.teamprojecte]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.teamprojecte]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
